<?php
/**
 * Set configuration variables
 *
 * PHP version 7
 *
 * @category  Publishing
 * @package   Online-News-Site
 * @author    Hardcover LLC <useTheContactForm@hardcoverwebdesign.com>
 * @copyright 2018 Hardcover LLC
 * @license   https://hardcoverwebdesign.com/license  MIT License
 *            https://hardcoverwebdesign.com/gpl-2.0  GNU General Public License, Version 2
 * @version:  2018 12 21
 * @link      https://hardcoverwebdesign.com/
 * @link      https://online-news-site.com/
 * @link      https://github.com/hardcover/
 */
//
// INPUT: Time zone offset from GMT, Greenwich Mean Time
// The following entries are allowed:
//   -12 -11 -10 -9 -8 -7 -6 -5 -4.30 -4 -3.30 -3 -2 -1 0
//   1 2 3 3.30 4 5 5.30 5.45 6 6.30 7 8 9 9.30 10 11 12 13
//
$gmtOffset = '-8';
//
// INPUT: Relative path to the includes folder, without trailing /
//
$includesPath = 'z/includes';
//
// INPUT: URI scheme, http or https
//
$uriScheme = 'https';
?>