  <link rel="icon" type="image/png" href="images/32.png" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="generator" content="Online News Site software, https://onlinenewssite.com/" />
  <link rel="stylesheet" type="text/css" href="z/base.css" />
  <link rel="stylesheet" type="text/css" href="z/article.css" />
  <link rel="manifest" href="manifest.json">
  <link rel="apple-touch-icon" href="images/192.png">
