  <link rel="icon" type="image/png" href="images/32.png">
  <link rel="stylesheet" type="text/css" href="z/base.css">
  <link rel="stylesheet" type="text/css" href="z/general.css">
  <link rel="manifest" href="manifest.json">
  <link rel="apple-touch-icon" href="images/192.png">
  <script src="z/cellMenu.js"></script>
  <meta name="generator" content="Online News Site https://onlinenewssite.com/">
