  <link rel="icon" type="image/png" href="z/images/favicon.png" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" type="text/css" href="https://onlinenewssite.com/example/z/base.css" />
  <link rel="stylesheet" type="text/css" media="(max-width: 1200px)" href="https://onlinenewssite.com/example/z/small-two.css" />
  <link rel="stylesheet" type="text/css" media="(min-width: 1200px)" href="https://onlinenewssite.com/example/z/large-two.css" />
