<?php
/**
 * An array of the categories of classified ads
 *
 * PHP version 7
 *
 * @category  Publishing
 * @package   Online-News-Site
 * @author    Hardcover LLC <useTheContactForm@hardcoverwebdesign.com>
 * @copyright 2016 Hardcover LLC
 * @license   http://hardcoverwebdesign.com/license  MIT License
 *.@license   http://hardcoverwebdesign.com/gpl-2.0  GNU General Public License, Version 2
 * @version:  2016-10-16
 * @link      http://hardcoverwebdesign.com/
 * @link      http://online-news-site.com/
 * @link      https://github.com/hardcover/
 */
$classifiedCategories = array(
'Community' => array(
    'Activities',
    'Artists',
    'Childcare',
    'Classes',
    'Events',
    'General',
    'Groups',
    'Local news',
    'Lost & found',
    'Musicians',
    'Pets',
    'Politics',
    'Rideshare',
    'Volunteers'),
'For sale' => array(
    'ATV, UTV & snow',
    'Antiques',
    'Appliances',
    'Arts & crafts',
    'Auto parts',
    'Baby & kid',
    'Barter',
    'Beauty & health',
    'Bikes',
    'Boats',
    'Books',
    'Business',
    'CDs, DVD & VHS',
    'Cars & trucks',
    'Cell phones',
    'Clothes & accessories',
    'Collectibles',
    'Computer',
    'Electronics',
    'Farm & garden',
    'Free',
    'Furniture',
    'Garage sale',
    'General',
    'Heavy equipment',
    'Household',
    'Jewelry',
    'Materials',
    'Motorcycles',
    'Music instruments',
    'Photo & video',
    'RVs & camping',
    'Sporting',
    'Tickets',
    'Tools',
    'Toys & games',
    'Video gaming',
    'Wanted'),
'Housing' => array(
    'Apts & housing',
    'Housing swap',
    'Housing wanted',
    'Office & commercial',
    'Parking & storage',
    'Real estate for sale',
    'Rooms & shared',
    'Sublets & temporary',
    'Vacation rentals'),
'Jobs' => array(
    'Accounting & finance',
    'Admin & office',
    'Architecture & engineering',
    'Art, media & design',
    'Biotech & science',
    'Business & mgmt',
    'Customer service',
    'Education',
    'Food, beverage & hospitality',
    'General labor',
    'Government',
    'Human resources',
    'Internet engineers',
    'Legal & paralegal',
    'Manufacturing',
    'Marketing, PR & advertising',
    'Medical & health',
    'Nonprofit sector',
    'Real estate',
    'Retail & wholesale',
    'Sales & business development',
    'Salon, spa & fitness',
    'Security',
    'Skilled trade & craft',
    'Software & QA',
    'Systems & networking',
    'TV, film & video',
    'Technical support',
    'Transport',
    'Web & information design',
    'Writing & editing',
    'Other'),
'Services' => array(
    'Automotive',
    'Beauty',
    'Computer',
    'Creative',
    'Cycle',
    'Event',
    'Farm & garden',
    'Financial',
    'Household',
    'Labor & moving',
    'Legal',
    'Lessons',
    'Marine',
    'Pet',
    'Real estate',
    'Skilled trade',
    'Small business ads',
    'Therapeutic',
    'Travel & vacation',
    'Write & edit')
);
?>