<?php
/**
 * An array of the categories of classified ads
 *
 * PHP version 8
 *
 * @category  Publishing
 * @package   Online_News_Site
 * @author    Hardcover LLC <useTheContactForm@hardcoverwebdesign.com>
 * @copyright 2025 Hardcover LLC
 * @license   https://hardcoverwebdesign.com/license  MIT License
 * @version:  2025 05 12
 * @link      https://hardcoverwebdesign.com/
 * @link      https://onlinenewssite.com/
 * @link      https://github.com/hardcover/
 */
$classifiedCategories = [
'Community' => [
    'Activities',
    'Artists',
    'Childcare',
    'Classes',
    'Events',
    'General',
    'Groups',
    'Local News',
    'Lost & Found',
    'Musicians',
    'Pets',
    'Politics',
    'Public Service Announcement',
    'Rideshare',
    'Volunteers'],
'For Sale' => [
    'ATV, UTV & Snow',
    'Antiques',
    'Appliances',
    'Arts & Crafts',
    'Auto Parts',
    'Baby & Kid',
    'Barter',
    'Beauty & Health',
    'Bikes',
    'Boats',
    'Books',
    'Business',
    'CDs, DVD & VHS',
    'Cars & Trucks',
    'Cell Phones',
    'Clothes & Accessories',
    'Collectibles',
    'Computer',
    'Electronics',
    'Farm & Garden',
    'Free',
    'Furniture',
    'Garage Sale',
    'General',
    'Heavy Equipment',
    'Household',
    'Jewelry',
    'Materials',
    'Motorcycles',
    'Music Instruments',
    'Photo & Video',
    'RVs & Camping',
    'Sporting',
    'Tickets',
    'Tools',
    'Toys & Games',
    'Video Gaming',
    'Wanted'],
'Housing' => [
    'Apts & Housing',
    'Housing Swap',
    'Housing Wanted',
    'Office & Commercial',
    'Parking & Storage',
    'Real Estate for Sale',
    'Rooms & Shared',
    'Sublets & Temporary',
    'Vacation Rentals'],
'Jobs' => [
    'Accounting & Finance',
    'Admin & Office',
    'Architecture & Engineering',
    'Art, Media & Design',
    'Biotech & Science',
    'Business & Mgmt',
    'Customer Service',
    'Education',
    'Food, Beverage & Hospitality',
    'General Labor',
    'Government',
    'Human Resources',
    'Internet Engineers',
    'Legal & paralegal',
    'Manufacturing',
    'Marketing, PR & Advertising',
    'Medical & Health',
    'Nonprofit Sector',
    'Real Estate',
    'Retail & Wholesale',
    'Sales & Business Development',
    'Salon, Spa & Fitness',
    'Security',
    'Skilled Trade & Craft',
    'Software & QA',
    'Systems & Networking',
    'TV, Film & Video',
    'Technical Support',
    'Transport',
    'Web & Information Design',
    'Writing & Editing',
    'Other'],
'Services' => [
    'Automotive',
    'Beauty',
    'Computer',
    'Creative',
    'Cycle',
    'Event',
    'Farm & Garden',
    'Financial',
    'Household',
    'Labor & Moving',
    'Legal',
    'Lessons',
    'Marine',
    'Pet',
    'Real Estate',
    'Skilled Trade',
    'Small Business Ads',
    'Therapeutic',
    'Travel & Vacation',
    'Write & Edit']
];
?>
