<?php
/**
 * Set configuration variables
 *
 * PHP version 8
 *
 * @category  Publishing
 * @package   Online_News_Site
 * @author    Online News <useTheContactForm@onlinenewssite.com>
 * @copyright 2025 Online News LLC
 * @license   https://onlinenewssite.com/license.html
 * @version   2025 05 12
 * @link      https://onlinenewssite.com/
 * @link      https://github.com/onlinenewsllc/online-news-site
 */
//
// INPUT: Time zone offset from GMT, Greenwich Mean Time
// The following entries are allowed:
//   -12 -11 -10 -9 -8 -7 -6 -5 -4.30 -4 -3.30 -3 -2 -1 0
//   1 2 3 3.30 4 5 5.30 5.45 6 6.30 7 8 9 9.30 10 11 12 13
//
$gmtOffset = '-8';
//
// INPUT: Relative path to the includes folder, without trailing /
//
$includesPath = 'editor/z/includes';
//
// INPUT: URI scheme, http or https
//
$uriScheme = 'https';
//
// INPUT: Access to news, free or paid
//
$freeOrPaid = 'free';
?>
